[package]
name = "rdkit-rs"
version = "0.1.0"
edition = "2021"
links = "shim2"

[dependencies]
bitflags = "2.4.1"
log = "0.4.20"
rdkit-sys = { git = "https://github.com/ntBre/rdkit-sys" }
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.114"